local-bin-path: bin/

resolver: lts-17.13

packages:
  - ext/cardano-node.git/cardano-node
  - ext/cardano-node.git/cardano-cli
  - ext/data-science.git/processes/cardano-block-follower
  #- ext/cardano-db-sync.git/cardano-db-sync

extra-deps:
  - ext/cardano-node.git/cardano-api
  - ext/cardano-node.git/cardano-config

  #- ext/cardano-db-sync.git/cardano-db

  - async-timer-0.2.0.0
  - base16-bytestring-1.0.1.0
  - canonical-json-0.6.0.0
  - dns-3.0.4
  - network-3.1.2.1
  - nothunks-0.1.2
  - partial-order-0.2.0.0
  - statistics-linreg-0.3
  - streaming-binary-0.2.2.0
  - transformers-except-0.1.1
  - unliftio-core-0.1.2.0


  - ext/ouroboros-network.git/typed-protocols
  - ext/ouroboros-network.git/typed-protocols-examples
  - ext/ouroboros-network.git/network-mux
  - ext/ouroboros-network.git/ouroboros-network
  - ext/ouroboros-network.git/ouroboros-network-framework
  - ext/ouroboros-network.git/ouroboros-network-testing
  - ext/ouroboros-network.git/ouroboros-consensus
  - ext/ouroboros-network.git/ouroboros-consensus-byron
  - ext/ouroboros-network.git/ouroboros-consensus-cardano
  - ext/ouroboros-network.git/ouroboros-consensus-shelley
  - ext/ouroboros-network.git/io-sim
  - ext/ouroboros-network.git/io-sim-classes

  - ext/cardano-ledger-specs.git/cardano-ledger-core
  - ext/cardano-ledger-specs.git/semantics/executable-spec
  - ext/cardano-ledger-specs.git/semantics/small-steps-test
  - ext/cardano-ledger-specs.git/byron/ledger/executable-spec
  - ext/cardano-ledger-specs.git/byron/ledger/impl
  - ext/cardano-ledger-specs.git/byron/ledger/impl/test
  - ext/cardano-ledger-specs.git/byron/crypto
  - ext/cardano-ledger-specs.git/byron/crypto/test
  - ext/cardano-ledger-specs.git/byron/chain/executable-spec
  - ext/cardano-ledger-specs.git/shelley/chain-and-ledger/dependencies/non-integer
  - ext/cardano-ledger-specs.git/shelley/chain-and-ledger/executable-spec
  - ext/cardano-ledger-specs.git/shelley/chain-and-ledger/shelley-spec-ledger-test
  - ext/cardano-ledger-specs.git/shelley-ma/impl
  - ext/cardano-ledger-specs.git/shelley-ma/shelley-ma-test

  - ext/cardano-prelude.git/cardano-prelude
  - ext/cardano-prelude.git/cardano-prelude-test

  - ext/iohk-monitoring-framework.git/contra-tracer
  - ext/iohk-monitoring-framework.git/tracer-transformers
  - ext/iohk-monitoring-framework.git/iohk-monitoring
  - ext/iohk-monitoring-framework.git/plugins/backend-aggregation
  - ext/iohk-monitoring-framework.git/plugins/backend-editor
  - ext/iohk-monitoring-framework.git/plugins/backend-ekg
  - ext/iohk-monitoring-framework.git/plugins/backend-kafka
  - ext/iohk-monitoring-framework.git/plugins/backend-monitoring
  - ext/iohk-monitoring-framework.git/plugins/backend-trace-acceptor
  - ext/iohk-monitoring-framework.git/plugins/backend-trace-forwarder
  - ext/iohk-monitoring-framework.git/plugins/scribe-systemd
  # deps by iohk-monitoring-framework
  - prometheus-2.2.2
  - libsystemd-journal-1.4.5
  - katip-0.8.5.0

  - ext/cardano-base.git/binary
  - ext/cardano-base.git/cardano-crypto-class
  - ext/cardano-base.git/cardano-crypto-praos
  - ext/cardano-base.git/slotting
  - ext/cardano-base.git/strict-containers

  - ext/cardano-crypto.git
  - ext/Win32-network.git

flags:
  cardano-crypto-praos:
    external-libsodium-vrf: true

# also set environment variable:
# export PKG_CONFIG_PATH=$(pwd)/ext/input-output-hk_libsodium.git/OUT/lib/pkgconfig:$PKG_CONFIG_PATH
extra-include-dirs:
  - ext/input-output-hk_libsodium.git/OUT/include
extra-lib-dirs:
  - ext/input-output-hk_libsodium.git/OUT/lib

# depends on Nix for dependencies, but can be turned off with (enable: false)
nix:
  enable: true
  pure: true
  shell-file: stack.nix
