local-bin-path: bin/

resolver: lts-18.9
compiler: ghc-8.10.7

packages:
  - ext/cardano-node.git/cardano-cli
  - ext/cardano-node.git/cardano-node
  - ext/cardano-node.git/cardano-api

extra-deps:
  - ext/cardano-node.git/cardano-config

  #- ext/cardano-db-sync.git/cardano-db-sync
  #- ext/cardano-db-sync.git/cardano-db

  - async-timer-0.2.0.0
  - base16-bytestring-1.0.1.0
  - canonical-json-0.6.0.0
  - dns-3.0.4
  - network-3.1.2.1
  - nothunks-0.1.2
  - partial-order-0.2.0.0
  - statistics-linreg-0.3
  - streaming-binary-0.2.2.0
  - transformers-except-0.1.1
  - unliftio-core-0.1.2.0

  - ext/ouroboros-network.git/io-sim
  - ext/ouroboros-network.git/io-classes
  - ext/ouroboros-network.git/monoidal-synchronisation
  - ext/ouroboros-network.git/network-mux
  - ext/ouroboros-network.git/ouroboros-consensus
  - ext/ouroboros-network.git/ouroboros-consensus-byron
  - ext/ouroboros-network.git/ouroboros-consensus-cardano
  - ext/ouroboros-network.git/ouroboros-consensus-shelley
  - ext/ouroboros-network.git/ouroboros-network
  - ext/ouroboros-network.git/ouroboros-network-framework
  - ext/ouroboros-network.git/ouroboros-network-testing
  - ext/ouroboros-network.git/typed-protocols
  - ext/ouroboros-network.git/typed-protocols-cborg
  - ext/ouroboros-network.git/typed-protocols-examples

  - ext/cardano-ledger-specs.git/eras/alonzo/impl
  - ext/cardano-ledger-specs.git/eras/alonzo/test-suite
  - ext/cardano-ledger-specs.git/eras/byron/chain/executable-spec
  - ext/cardano-ledger-specs.git/eras/byron/crypto
  - ext/cardano-ledger-specs.git/eras/byron/crypto/test
  - ext/cardano-ledger-specs.git/eras/byron/ledger/executable-spec
  - ext/cardano-ledger-specs.git/eras/byron/ledger/impl
  - ext/cardano-ledger-specs.git/eras/byron/ledger/impl/test
  - ext/cardano-ledger-specs.git/eras/shelley/impl
  - ext/cardano-ledger-specs.git/eras/shelley/test-suite
  - ext/cardano-ledger-specs.git/eras/shelley-ma/impl
  - ext/cardano-ledger-specs.git/eras/shelley-ma/test-suite
  - ext/cardano-ledger-specs.git/libs/cardano-ledger-core
  - ext/cardano-ledger-specs.git/libs/cardano-ledger-pretty
  - ext/cardano-ledger-specs.git/libs/cardano-protocol-tpraos
  - ext/cardano-ledger-specs.git/libs/small-steps
  - ext/cardano-ledger-specs.git/libs/small-steps-test
  - ext/cardano-ledger-specs.git/libs/non-integral
  - ext/cardano-ledger-specs.git/eras/shelley/chain-and-ledger/executable-spec
  - ext/cardano-ledger-specs.git/eras/shelley/chain-and-ledger/shelley-spec-ledger-test
  - ext/cardano-ledger-specs.git/eras/shelley/chain-and-ledger/dependencies/non-integer

  - ext/cardano-prelude.git/cardano-prelude
  - ext/cardano-prelude.git/cardano-prelude-test

  - ext/iohk-monitoring-framework.git/contra-tracer
  - ext/iohk-monitoring-framework.git/tracer-transformers
  - ext/iohk-monitoring-framework.git/iohk-monitoring
  - ext/iohk-monitoring-framework.git/plugins/backend-aggregation
  - ext/iohk-monitoring-framework.git/plugins/backend-editor
  - ext/iohk-monitoring-framework.git/plugins/backend-ekg
  - ext/iohk-monitoring-framework.git/plugins/backend-kafka
  - ext/iohk-monitoring-framework.git/plugins/backend-monitoring
  - ext/iohk-monitoring-framework.git/plugins/backend-trace-acceptor
  - ext/iohk-monitoring-framework.git/plugins/backend-trace-forwarder
  - ext/iohk-monitoring-framework.git/plugins/scribe-systemd
  # deps by iohk-monitoring-framework
  - prometheus-2.2.2
  - libsystemd-journal-1.4.5
  - katip-0.8.5.0

  - ext/cardano-base.git/base-deriving-via
  - ext/cardano-base.git/binary
  - ext/cardano-base.git/binary/test
  - ext/cardano-base.git/cardano-crypto-class
  - ext/cardano-base.git/cardano-crypto-praos
  - ext/cardano-base.git/measures
  - ext/cardano-base.git/orphans-deriving-via
  - ext/cardano-base.git/slotting
  - ext/cardano-base.git/strict-containers

  - ext/cardano-crypto.git
  - ext/Win32-network.git

  - ext/plutus.git/freer-extras
  - ext/plutus.git/plutus-core
  - ext/plutus.git/plutus-ledger
  - ext/plutus.git/plutus-ledger-api
  - ext/plutus.git/plutus-tx
  - ext/plutus.git/plutus-tx-plugin
  - ext/plutus.git/prettyprinter-configurable
  - ext/plutus.git/stubs/plutus-ghc-stub
  - ext/plutus.git/word-array

    # extra deps
  - Unique-0.4.7.8@sha256:9661f45aa31dde119a2114566166ea38b011a45653337045ee4ced75636533c0,2067
  - composition-prelude-3.0.0.2@sha256:1ffed216bd28d810fce0b5be83a661e2a892696d73b3f8de5c0f5edb9b5f0090,1216
  - lazy-search-0.1.2.1@sha256:c942a01e4a64881f89c72eaef5e3a78eba8750759cd66996c6746a2a7cabe703,1199
  - monoidal-containers-0.6.0.1@sha256:f56ea8fe91ff93da140e38b8dab4b94437b901818c13ba72fc7fc802290323ee,2583
  - moo-1.2@sha256:0c4be1a01548db785dcbbe6b8c98579dbf03c5b3b536e0420dce3ba6a61337cb,5951
  - size-based-0.1.2.0@sha256:1b33da89d270189661dbbda49a88b0c21d2fc2f7a407e7a2b1933e2faf0f5d4d,1258
  - gray-code-0.3.1@sha256:2c8a4ed9c9ee37320305610604d6d93504e0813d7c9768949af418b53043185a,2388
  - dom-lt-0.2.3@sha256:89f17bbeb0d23f5a46fe7099b81cc9b4b5df32aadb5080fc171c874aafc802c0,1850

  - git: https://github.com/input-output-hk/goblins
    commit: cde90a2b27f79187ca8310b6549331e59595e7ba
  - git: https://github.com/input-output-hk/optparse-applicative
    commit: 7497a29cb998721a9068d5725d49461f2bba0e7a
  - git: https://github.com/input-output-hk/flat
    commit: ee59880f47ab835dbd73bea0847dab7869fc20d8
  - git: https://github.com/input-output-hk/hedgehog-extras
    commit: edf6945007177a638fbeb8802397f3a6f4e47c14
  - git: https://github.com/input-output-hk/ekg-forward
    commit: d9e8fd302fa6ba41c07183d371e6777286d37bc2

allow-newer: true

flags:
  cardano-crypto-praos:
    external-libsodium-vrf: true

ghc-options:
  '$everything': -haddock

# also set environment variable:
# export PKG_CONFIG_PATH=$(pwd)/ext/input-output-hk_libsodium.git/OUT/lib/pkgconfig:$PKG_CONFIG_PATH
extra-include-dirs:
  - ext/input-output-hk_libsodium.git/OUT/include
extra-lib-dirs:
  - ext/input-output-hk_libsodium.git/OUT/lib

# use Nix for dependencies: can be turned on with (enable: true)
nix:
  enable: false
  pure: false
  shell-file: stack.nix
