local-bin-path: bin/

resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/00487726c4bc21b4744e59d913334ebfeac7d68e/snapshot.yaml

packages:
  - ext/cardano-node.git/cardano-node
  - ext/cardano-db-sync.git/cardano-db-sync


extra-deps:
  - ext/cardano-node.git/cardano-config
  # deps by cardano-node
  - bimap-0.4.0
  - binary-0.8.7.0
  - brick-0.47
  - config-ini-0.2.4.0
  - containers-0.5.11.0
  - data-clist-0.1.2.2
  - esqueleto-3.2.2
  - generic-monoid-0.1.0.0
  - gray-code-0.3.1
  - io-streams-1.5.1.0
  - io-streams-haproxy-1.0.1.0
  - moo-1.2
  - network-3.1.0.0
  - persistent-2.10.5.1
  - persistent-postgresql-2.10.1.2
  - persistent-template-2.8.2.3
  - snap-core-1.0.4.0
  - snap-server-1.1.1.1
  - statistics-linreg-0.3
  - tasty-hedgehog-1.0.0.1
  - text-zipper-0.10.1
  - th-lift-0.8.1
  - th-lift-instances-0.1.14
  - transformers-except-0.1.1
  - Unique-0.4.7.6
  - word-wrap-0.4.1
  - websockets-0.12.6.1

  - ext/ouroboros-network.git/typed-protocols
  - ext/ouroboros-network.git/typed-protocols-examples
  - ext/ouroboros-network.git/ouroboros-network-framework
  - ext/ouroboros-network.git/network-mux
  - ext/ouroboros-network.git/ouroboros-network
  - ext/ouroboros-network.git/ouroboros-consensus
  - ext/ouroboros-network.git/ouroboros-consensus-cardano
  - ext/ouroboros-network.git/ouroboros-consensus-byron
  - ext/ouroboros-network.git/ouroboros-consensus/ouroboros-consensus-mock
  - ext/ouroboros-network.git/io-sim
  - ext/ouroboros-network.git/io-sim-classes

  - ext/cardano-ledger.git/cardano-ledger
  - ext/cardano-ledger.git/cardano-ledger/test
  - ext/cardano-ledger.git/crypto
  - ext/cardano-ledger.git/crypto/test

  - ext/cardano-ledger-specs.git/byron/semantics/executable-spec
  - ext/cardano-ledger-specs.git/byron/ledger/executable-spec
  - ext/cardano-ledger-specs.git/byron/chain/executable-spec

  - ext/goblins.git/

  - ext/cardano-prelude.git
  - ext/cardano-prelude.git/test

  - ext/iohk-monitoring-framework.git/contra-tracer
  - ext/iohk-monitoring-framework.git/tracer-transformers
  - ext/iohk-monitoring-framework.git/iohk-monitoring
  - ext/iohk-monitoring-framework.git/plugins/backend-monitoring
  - ext/iohk-monitoring-framework.git/plugins/backend-aggregation
  - ext/iohk-monitoring-framework.git/plugins/backend-ekg
  - ext/iohk-monitoring-framework.git/plugins/backend-editor
  - ext/iohk-monitoring-framework.git/plugins/scribe-systemd
  # deps by iohk-monitoring-framework
  - time-units-1.0.0
  - prometheus-2.1.2
  - libsystemd-journal-1.4.4
  - katip-0.8.3.0

  - ext/cardano-base.git/binary
  - ext/cardano-base.git/binary/test
  - ext/cardano-base.git/cardano-crypto-class
  - ext/cardano-base.git/slotting

  - ext/cardano-crypto.git
  - ext/cardano-sl-x509.git

  - ext/cardano-shell.git/cardano-launcher
  - ext/cardano-shell.git/cardano-shell

  - ext/cardano-db-sync.git/cardano-db


flags:
  cardano-ledger:
    development: true

  cardano-crypto-class:
    development: true

nix:
  pure: true
  packages: [ zlib.dev, zlib.out
            , openssl.dev, openssl.out
            , haskell.compiler.ghc865
            , pkg-config
            , systemd.dev
            , postgresql
            ]
